### ISSUE TITLE
На экране цикла не отображается его содержание

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#119]

**Comment by HombreTech** [comment]
Было бы лучше, если бы мы знали - цикл это или отдельное произведение (work_type_id), т.к. иначе  будет пустая вкладка с содержанием у отдельного произведения.
На данный момент тип work`а есть у отзыва, списка автора, но нет у результатов поиска по произведениям.

**Comment by kenrube** [comment]
А вкладки создаются до того, как загрузилось содержимое из сети?

**Comment by HombreTech** [comment]
Pager формируется вообще до отображения вкладок.

**Comment by kenrube** [comment]
Блин, плохо. Попробую уболтать @Mazian, чтоб добавил `work_type_id` в результаты поиска. Если не срастется - предлагаю оставить вкладку, написать что-нибудь вроде "Нет вложенных произведений"

**Comment by kenrube** [comment]
Завел таску: https://github.com/FantLab/FantLab-API/issues/37

**Comment by HombreTech** [comment]
Обошелся малыми жертвами. В результатах поиска есть поле **name_eng**, которое содержит название типа в оригинале. Создал **enum**, в котором для поиска проверяем **name == cycle**, а для остальных по **type_id** смотрим.
