### ISSUE TITLE
Проапдейтить прогвард

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#121]
Чтоб собиралась релизная сборка

**Comment by kenrube** [comment]
В релизной версии в рантайме падают любые запросы, выкидывающие исключения - проблема в `Timber->tag`.

**Comment by HombreTech** [comment]
@kenrube пофиксишь или мне посмотреть?

**Comment by kenrube** [comment]
Если есть время - глянь, пожалуйста. Я пока кеширование в свободное время доделываю

**Comment by kenrube** [comment]
Для примера - поиск при отключенной сети
