### ISSUE TITLE
Список циклов автора

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#39]
Вывести вверху экрана со списком произведений список блоков с циклами (условные циклы, межавторские проекты etc). Все данные берем из базы.

Необходимо продумать, как обозначать уровень вложенности произведения (скорее всего, отступом карточки слева) и цикло-специфичную информацию (бонус; авторы/соавторы).

При клике на конкретный цикл/произведение переход на соответствующий экран.

В рамках данной задачи:
1. Сворачивание блоков не делаем
2. Не делаем сложной сортировки.

**Comment by HombreTech** [comment]
Считаем выполненным?
