### ISSUE TITLE
Список оценок пользователя

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#59]
Вывести список оцененных пользователем произведений. Информацию взять из базы.

Карточка произведения должна включать:
1. Автор
2. Название
3. Название в оригинале (если есть)
4. Тип
5. Год написания/издания
6. Ссылка на произведение. По клику переход на экран конкретного произведения
7. Текущая оценка (+ возможность ее изменить)
8. Классифицировано или нет
9. Есть отзыв или нет

В рамках данной задачи:
1. Не реализуем сортировку
2. Не реализуем фильтрацию по категориям
3. Не отображаем список наиболее оцененных авторов
4. Не отображаем гистограммы

**Comment by HombreTech** [comment]
Считать выполненным?

**Comment by kenrube** [comment]
Да, закрывай
