### ISSUE TITLE
FastScroller отсутствует на экране поиска

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#65]

**Comment by HombreTech** [comment]
А, собственно, зачем он там?

**Comment by kenrube** [comment]
Для удобства - как и любой скроллбар, во-первых, показывает позицию скролла, во-вторых, позволяет быстро прокрутить куда следует. В Fasthub он есть (синий сбоку), у нас куда-то потерялся - возможно, при конвертации java-класса в Котлин.
