### ISSUE TITLE
Проапдейтить drawer до актуального состояния

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#81]
Разнести общую информацию и информацию профиля по разным вкладкам, как это сделано сейчас в FastHub.

**Comment by HombreTech** [comment]
Не ясно что нужно сделать, также как и в https://github.com/FantLab/FantLab-client/issues/29

**Comment by kenrube** [comment]
Поправил. Про "букашку" из #29: на сайте вверху каждой страницы есть букашка, которую по клику можно убить и воскресить обратно. Была мысль добавить тот же функционал в боковое меню - неплохо нервы расслабляет. Ну и маскот фантлаба, как-никак
