### ISSUE TITLE
Классификацию в ворке отображать в том же стиле, что и Классификатор

### ISSUE THREAD

**Issue by kenrube** [FantLab/FantLab-client#94]
То есть сделать сворачивание/разворачивание при клике (без чекбоксов и изначально полностью раскрытый). Сейчас классификация отдается полностью, так что можно добавить и отображение процентов, за какой пункт сколько человек проголосовало

**Comment by HombreTech** [comment]
Частично сделал, остальное пока под вопросом.

**Comment by kenrube** [comment]
На чем застопорился?
